In [ ]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn/model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltknltk.download("stopwords)

In [ ]:
print(stopwords("English"))

ML model

In [ ]:
df = pd.read_csv()
df.shape

In [ ]:
df.head()

In [102]:
import pandas as pd
import numpy as np

# Sample dataset
data = {
'Milk': [1, 1, 0, 1, 0],
'Bread': [1, 0, 1, 1, 1],
'Butter': [0, 1, 1, 1, 1],
'Eggs': [1, 0, 0, 1, None]
}
df = pd.DataFrame(data)
df

   Milk  Bread  Butter  Eggs
0     1      1       0   1.0
1     1      0       1   0.0
2     0      1       1   0.0
3     1      1       1   1.0
4     0      1       1   NaN

In [103]:
df.dropna()

   Milk  Bread  Butter  Eggs
0     1      1       0   1.0
1     1      0       1   0.0
2     0      1       1   0.0
3     1      1       1   1.0

In [12]:
df2 =  pd.read_csv(r"C:\Users\HP\Downloads\sample_data.csv")

In [53]:
df2.loc[0:1]

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   50000
1   2    Bob   30    Finance   60000

In [61]:
df2['Age'] > 30

0    False
1    False
2     True
3     True
4    False
Name: Age, dtype: bool

In [71]:
df2.loc[[False,False,True,True,False]]

   ID     Name  Age Department  Salary
2   3  Charlie   35         IT   75000
3   4    David   40  Marketing   80000

In [58]:
df2.loc[df2['Age'] > 30]

   ID     Name  Age Department  Salary
2   3  Charlie   35         IT   75000
3   4    David   40  Marketing   80000

In [74]:
df2.query('Age> 30')

   ID     Name  Age Department  Salary
2   3  Charlie   35         IT   75000
3   4    David   40  Marketing   80000

In [142]:
print(df['Eggs'].replace(np.nan, "ab",inplace=True))

None

In [159]:
df

   Milk  Bread  Butter Eggs
0     1      1       0  1.0
1     1      0       1  0.0
2     0      1       1  0.0
3     1      1       1  1.0
4     0      1       1   ab

In [160]:
print(df.groupby('Eggs').transform(lambda x: x.min()))

   Milk  Bread  Butter
0     1      1       0
1     0      0       1
2     0      0       1
3     1      1       0
4     0      1       1

In [162]:
print(df.groupby('Eggs').apply(lambda x: x.max()))

      Milk  Bread  Butter Eggs
Eggs
0.0      1      1       1  0.0
1.0      1      1       1  1.0
ab       0      1       1   ab

C:\Users\HP\AppData\Local\Temp\ipykernel_6252\2439316879.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  print(df.groupby('Eggs').apply(lambda x: x.max()))

In [54]:
x = [1, 2, 3]
y = x
y.append(4)
print(x)

[1, 2, 3, 4]

In [105]:
arr = np.array([[1, 2, 3],[4,5,6],[7,88,9]])

In [121]:
print(arr)
print(arr.sum(axis=0)) # Sum along columns
print(arr.sum(axis=1))  # Sum along rows
print(arr.var()) # Mean along columns

[[ 1  2  3]
 [ 4  5  6]
 [ 7 88  9]]
[12 95 18]
[  6  15 104]
692.0987654320987

In [163]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print(A+B)

[[11 22]
 [13 24]]